/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./components/Board.vue')['default']
    Cell: typeof import('./components/Cell.vue')['default']
    CenterContents: typeof import('./components/CenterContents/index.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    GameInfo: typeof import('./components/GameInfo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LeftSideMenu: typeof import('./components/LeftSideMenu/index.vue')['default']
    Radio: typeof import('./components/Radio.vue')['default']
    Result: typeof import('./components/Result.vue')['default']
    RightSideMenu: typeof import('./components/RightSideMenu/index.vue')['default']
    RootContainer: typeof import('./components/RootContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingStart: typeof import('./components/SettingStart.vue')['default']
    Stone: typeof import('./components/Stone.vue')['default']
  }
}
